services:
  postgres:
    image: postgres:16
    container_name: healthops_pg
    environment:
      POSTGRES_USER: healthops
      POSTGRES_PASSWORD: healthops
      POSTGRES_DB: healthops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/sql:ro

volumes:
  pgdata:
